### ISSUE TITLE
loadAllDBFileMetrics fails with DB names having "-" or  dot "." in Name

### ISSUE THREAD

**Issue by eliassal** [ericcobb/SQL-Server-Metrics-Pack#3]
Hi, thanks for making this available for the community. I faced an issue when running oadAllDBFileMetrics. It fails on DBs whe they have a dash or dot in the names.
Thanks for your help

**Comment by ericcobb** [comment]
Thanks!  I've run into this issue before and just committed a bug fix for it.

**Comment by eliassal** [comment]
Thansk for your prompt response
